name: Deploy
on:
  push:
    branches: [master]
    
jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    
    steps:
    - name: install ssh keys command
      run: |
        install -m 600 -D /dev/null ~/.ssh/id_rsa
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.SSH_DEV_HOST }} > ~/.ssh/known_hosts
    - name: connect and pull
      run: ssh ${{ secrets.SSH_USER }}@{{ secrets.SSH_DEV_HOST }} -p 15822 "whoami"
    - name: cleanup
      run: rm -rf ~/.ssh
        
