name: Deploy
on:
  push:
    branches: [master]
    
jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        port: ${{ secrets.PORT }}
        key: ${{ secrets.KEY }}
        script: whoami
