name: Deploy
on:
  push:
    branches: [master]
    
jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v0.1.4
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: whoami
