name: Deploy
on:
  push:
    branches: [master]
    
jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_DEV_HOST }}
        username: ${{ secrets.SSH_USER }}
        port: 15822
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: ./deploy.sh
